# Generated by Django 5.1.6 on 2025-07-27 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tournament_tournamentmatch_tournamentparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='admin_decision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='creator_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duel',
            name='creator_proof',
            field=models.ImageField(blank=True, null=True, upload_to='duel_proofs/'),
        ),
        migrations.AddField(
            model_name='duel',
            name='dispute_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opponent_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_proof',
            field=models.ImageField(blank=True, null=True, upload_to='duel_proofs/'),
        ),
        migrations.AddField(
            model_name='duel',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('ongoing', 'En cours'), ('waiting_proof', 'En attente de preuve'), ('disputed', 'Litige'), ('completed', 'Terminé'), ('expired', 'Expiré')], default='open', max_length=20),
        ),
    ]
