# Generated by Django 5.1.6 on 2025-07-27 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_duel_admin_decision_duel_creator_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur'), ('super_admin', 'Super Administrateur')], default='user', max_length=20),
        ),
    ]
