# Generated by Django 5.1.6 on 2025-07-28 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duel',
            old_name='tickets',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='duel',
            old_name='resolved_at',
            new_name='completed_at',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='admin_decision',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='creator_claim',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='creator_proof',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='dispute_reason',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='game',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='opponent_claim',
        ),
        migrations.RemoveField(
            model_name='duel',
            name='opponent_proof',
        ),
        migrations.AddField(
            model_name='duel',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='ai_detected_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='ai_validation_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='creator_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='creator_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='duel_screenshots/'),
        ),
        migrations.AddField(
            model_name='duel',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='duel',
            name='game_type',
            field=models.CharField(choices=[('match_foot', 'Match de Foot'), ('penalty_shootout', 'Tirs au But'), ('ultimate_team', 'Ultimate Team'), ('freestyle', 'Freestyle'), ('build_fight', 'Build Fight'), ('box_fight', 'Box Fight'), ('zone_wars', 'Zone Wars'), ('1v1_sniper', 'Sniper 1v1'), ('tir_precis', 'Tir de Précision'), ('combat_rapide', 'Combat Rapide'), ('gunfight', 'Gunfight'), ('course_aerienne', 'Course Aérienne'), ('dribble_challenge', 'Dribble Challenge'), ('defi_aim', 'Défi Aim'), ('clutch_1v1', 'Clutch 1v1'), ('headshot_only', 'Headshot Only'), ('knife_fight', 'Knife Fight'), ('quick_scope', 'Quick Scope'), ('trick_shot', 'Trick Shot'), ('speedrun', 'Speedrun'), ('survival', 'Survival'), ('deathrun', 'Deathrun'), ('parkour', 'Parkour')], default='1v1_sniper', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_action',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='duel_screenshots/'),
        ),
        migrations.AddField(
            model_name='duel',
            name='original_duel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.duel'),
        ),
        migrations.AddField(
            model_name='duel',
            name='rematch_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematch_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('open', 'Ouvert'), ('waiting', 'En attente du second joueur'), ('active', 'Duel en cours'), ('upload_proof', 'Upload de preuves'), ('ai_validation', 'Validation IA'), ('waiting_confirmation', 'En attente de confirmation'), ('disputed', 'Litige'), ('completed', 'Terminé'), ('expired', 'Expiré')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(choices=[('match_foot', 'Match de Foot'), ('penalty_shootout', 'Tirs au But'), ('ultimate_team', 'Ultimate Team'), ('freestyle', 'Freestyle'), ('build_fight', 'Build Fight'), ('box_fight', 'Box Fight'), ('zone_wars', 'Zone Wars'), ('1v1_sniper', 'Sniper 1v1'), ('tir_precis', 'Tir de Précision'), ('combat_rapide', 'Combat Rapide'), ('gunfight', 'Gunfight'), ('course_aerienne', 'Course Aérienne'), ('dribble_challenge', 'Dribble Challenge'), ('defi_aim', 'Défi Aim'), ('clutch_1v1', 'Clutch 1v1'), ('headshot_only', 'Headshot Only'), ('knife_fight', 'Knife Fight'), ('quick_scope', 'Quick Scope'), ('trick_shot', 'Trick Shot'), ('speedrun', 'Speedrun'), ('survival', 'Survival'), ('deathrun', 'Deathrun'), ('parkour', 'Parkour')], max_length=20),
        ),
    ]
