# Generated by Django 5.1.6 on 2025-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_tickets_duel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='creator_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='opponent_ready',
            field=models.BooleanField(default=False),
        ),
    ]
