# Generated by Django 5.1.6 on 2025-07-28 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_duel_creator_ready_duel_opponent_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='admin_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='admin_resolution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='duel',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duel',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_duels', to=settings.AUTH_USER_MODEL),
        ),
    ]
