# Generated by Django 5.1.6 on 2025-07-28 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulaire du compte'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_euros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant en euros')),
                ('amount_tickets', models.PositiveIntegerField(verbose_name='Tickets déduits')),
                ('bank_account_holder', models.CharField(max_length=100, verbose_name='Titulaire du compte')),
                ('bank_iban', models.CharField(max_length=34, verbose_name='IBAN')),
                ('bank_bic', models.CharField(max_length=11, verbose_name='BIC/SWIFT')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, verbose_name='Notes administrateur')),
                ('transaction_id', models.CharField(blank=True, max_length=50, verbose_name='ID de transaction simulé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
