# Generated by Django 5.1.6 on 2025-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_bank_account_holder_user_bank_bic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adresse complète'),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_kyc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Prénom (KYC)'),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.CharField(blank=True, max_length=255, verbose_name="Pièce d'identité (simulé)"),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Compte vérifié'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_kyc',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nom (KYC)'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='proof_of_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Justificatif de domicile (simulé)'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notes de vérification (admin)'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
