# Generated by Django 5.1.6 on 2025-07-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_address_user_date_of_birth_user_first_name_kyc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom de la banque'),
        ),
        migrations.AddField(
            model_name='user',
            name='bic',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='BIC/SWIFT'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='user',
            name='iban',
            field=models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Code postal'),
        ),
    ]
